import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        tertiaryFixed: '#ffdf93',
        surfaceContainerHigh: '#ece6ee',
        onError: '#ffffff',
        onTertiaryFixedVariant: '#594400',
        primaryFixed: '#e9ddff',
        onSecondaryFixedVariant: '#4b4263',
        onSecondary: '#ffffff',
        outline: '#7a7582',
        surfaceContainerLow: '#f8f2fa',
        tertiaryContainer: '#c9a74d',
        primaryContainer: '#6750a4',
        onPrimaryFixedVariant: '#4f378a',
        onTertiaryContainer: '#503d00',
        onTertiary: '#ffffff',
        surfaceTint: '#6750a4',
        background: '#fdf7ff',
        tertiaryFixedDim: '#e7c365',
        surfaceContainerLowest: '#ffffff',
        surfaceDim: '#ded8e0',
        onPrimaryContainer: '#e0d2ff',
        primaryFixedDim: '#cfbcff',
        onErrorContainer: '#93000a',
        onSecondaryFixed: '#1f1635',
        inverseOnSurface: '#f5eff7',
        surfaceContainer: '#f2ecf4',
        primary: '#4f378a',
        error: '#ba1a1a',
        secondaryFixed: '#e9ddff',
        onTertiaryFixed: '#241a00',
        surfaceContainerHighest: '#e6e0e9',
        outlineVariant: '#cbc4d2',
        onBackground: '#1d1b20',
        onSecondaryContainer: '#645a7d',
        tertiary: '#765b00',
        inverseSurface: '#322f35',
        onPrimaryFixedVariant: '#22005d',
        surface: '#fdf7ff',
        onSurfaceVariant: '#494551',
        inversePrimary: '#cfbcff',
        onPrimary: '#ffffff',
        onSurface: '#1d1b20',
        errorContainer: '#ffdad6',
        surfaceBright: '#fdf7ff',
        secondaryContainer: '#e1d4fd',
        surfaceVariant: '#e6e0e9',
        secondary: '#63597c',
        secondaryFixedDim: '#cdc0e9',
        emeraldAi: '#10b981',
        electricIndigo: '#6366f1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        bentoGap: '20px',
        md: '24px',
        xl: '64px',
        lg: '40px',
        base: '4px',
        sm: '16px',
      },
      fontFamily: {
        display: ['Inter'],
        bodySm: ['Inter'],
        bodyLg: ['Inter'],
        h2: ['Inter'],
        labelCaps: ['Inter'],
        monoData: ['JetBrains Mono'],
        h1: ['Inter'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        bodySm: ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        bodyLg: ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        labelCaps: ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        monoData: ['13px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '500' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config;